<a href="https://colab.research.google.com/github/Tobeodeh/CSC-231-ASSIGNMENT/blob/main/222470_CHRIS_ODEH_CSC_ASS2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Needed libraries

In [38]:
import pandas as pd

Reading Data

In [1]:
path = "https://scipython.com/static/media/2/problems/P2.6/redwood-data.txt"

In [17]:
data = pd.read_csv(path,sep="\t",header = None, names=["Tree name","Location","Diameter(m)","Height(m)"])
data

,Tree name,Location,Diameter(m),Height(m)
0,# Coast Redwood data from The Gymnosperm datab...,NaN,NaN,NaN
1,"# Tree name, Location, diameter (m), height (m)",NaN,NaN,NaN
2,Aether's Arrow,Humboldt Redwoods State Park,3.38,111.16
3,Alice Rhodes,Humboldt Redwoods State Park,3.35,111.53
4,Apex,Humboldt Redwoods State Park,3.38,111.83
5,Crown Jewel,Redwood National Park,3.54,110.40
6,Daedalus,Redwood National Park,4.26,110.77
7,Federation Giant,Humboldt Redwoods State Park,4.54,112.62
8,Harriett Weaver,Humboldt Redwoods State Park,4.11,110.68
9,Harry Cole,Redwood National Park,4.94,111.65
10,Helios,Redwood National Park,4.96,114.58
11,Hyperion,Redwood National Park,4.84,115.61
12,Icarus,Redwood National Park,3.78,113.14
13,John Muir,Humboldt Redwoods State Park,4.27,110.06
14,Libby (A.K.A. Tall),Redwood National Park,2.90,110.62
15,Lone Fern,Humboldt Redwoods State Park,2.56,111.47
16,Mendocino,Montgomery Woods State Reserve,4.19,112.32
17,Millennium,Humboldt Redwoods State Park,2.71,111.92
18,Minaret,Humboldt Redwoods State Park,3.66,111.56
19,Mother & Daughter,Humboldt Redwoods State Park,3.60,111.50
20,National Geographic,Redwood National Park,4.39,112.71
21,Orion,Redwood National Park,4.33,112.63
22,Paradox,Humboldt Redwoods State Park,3.90,112.51
23,Paul Zahl,Redwood National Park,3.78,111.16
24,Paul Zinke,Humboldt Redwoods State Park,2.90,111.31
25,Pinnacle,Humboldt Redwoods State Park,3.05,110.71
26,Pipe Dream,Humboldt Redwoods State Park,4.27,111.71
27,Pyramid Giant,Humboldt Redwoods State Park,5.03,110.68
28,Rockefeller,Humboldt Redwoods State Park,4.84,111.59
29,Rocket Top,Humboldt Redwoods State Park,3.29,110.77
30,Rockview,Humboldt Redwoods State Park,3.84,110.03
31,South Fork,Humboldt Redwoods State Park,4.02,110.40
32,Springing Buck,Humboldt Redwoods State Park,4.79,110.20
33,Stratosphere Giant,Humboldt Redwoods State Park,5.18,113.05
34,Swamp,Montgomery Woods State Reserve,3.41,110.09
35,T4,Redwood National Park,3.99,110.06
36,Teepee Bell,Montgomery Woods State Reserve,4.08,111.34
37,Tranquility,Humboldt Redwoods State Park,4.14,110.55
38,Valentine,Humboldt Redwoods State Park,3.47,110.65

Dropping NAN values

In [18]:
new_data = data.dropna()
new_data

,Tree name,Location,Diameter(m),Height(m)
2,Aether's Arrow,Humboldt Redwoods State Park,3.38,111.16
3,Alice Rhodes,Humboldt Redwoods State Park,3.35,111.53
4,Apex,Humboldt Redwoods State Park,3.38,111.83
5,Crown Jewel,Redwood National Park,3.54,110.40
6,Daedalus,Redwood National Park,4.26,110.77
7,Federation Giant,Humboldt Redwoods State Park,4.54,112.62
8,Harriett Weaver,Humboldt Redwoods State Park,4.11,110.68
9,Harry Cole,Redwood National Park,4.94,111.65
10,Helios,Redwood National Park,4.96,114.58
11,Hyperion,Redwood National Park,4.84,115.61
12,Icarus,Redwood National Park,3.78,113.14
13,John Muir,Humboldt Redwoods State Park,4.27,110.06
14,Libby (A.K.A. Tall),Redwood National Park,2.90,110.62
15,Lone Fern,Humboldt Redwoods State Park,2.56,111.47
16,Mendocino,Montgomery Woods State Reserve,4.19,112.32
17,Millennium,Humboldt Redwoods State Park,2.71,111.92
18,Minaret,Humboldt Redwoods State Park,3.66,111.56
19,Mother & Daughter,Humboldt Redwoods State Park,3.60,111.50
20,National Geographic,Redwood National Park,4.39,112.71
21,Orion,Redwood National Park,4.33,112.63
22,Paradox,Humboldt Redwoods State Park,3.90,112.51
23,Paul Zahl,Redwood National Park,3.78,111.16
24,Paul Zinke,Humboldt Redwoods State Park,2.90,111.31
25,Pinnacle,Humboldt Redwoods State Park,3.05,110.71
26,Pipe Dream,Humboldt Redwoods State Park,4.27,111.71
27,Pyramid Giant,Humboldt Redwoods State Park,5.03,110.68
28,Rockefeller,Humboldt Redwoods State Park,4.84,111.59
29,Rocket Top,Humboldt Redwoods State Park,3.29,110.77
30,Rockview,Humboldt Redwoods State Park,3.84,110.03
31,South Fork,Humboldt Redwoods State Park,4.02,110.40
32,Springing Buck,Humboldt Redwoods State Park,4.79,110.20
33,Stratosphere Giant,Humboldt Redwoods State Park,5.18,113.05
34,Swamp,Montgomery Woods State Reserve,3.41,110.09
35,T4,Redwood National Park,3.99,110.06
36,Teepee Bell,Montgomery Woods State Reserve,4.08,111.34
37,Tranquility,Humboldt Redwoods State Park,4.14,110.55
38,Valentine,Humboldt Redwoods State Park,3.47,110.65

Finding the tree with the largest diameter

In [35]:
#This code prints out the entire row of the tree with the widest diameter and drops the height column
wide_diameter = new_data[new_data["Diameter(m)"]==new_data["Diameter(m)"].max()]
wide_diametern = wide_diameter.drop(columns = "Height(m)")
print(wide_diametern)

             Tree name                      Location  Diameter(m)
33  Stratosphere Giant  Humboldt Redwoods State Park         5.18

Finding the tallest tree

In [36]:
#This code checks for the tallest tree and prints out the entire row and then drops the diameter column

large_tree = new_data[new_data["Height(m)"]==new_data["Height(m)"].max()]
large_treen = large_tree.drop(columns="Diameter(m)")
print(large_treen)

   Tree name               Location  Height(m)
11  Hyperion  Redwood National Park     115.61